# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

In [2]:
a1=np.random.random((3,3,3))
print(a1)

[[[0.22908559 0.31603832 0.90083865]
  [0.2801303  0.97725589 0.99726892]
  [0.81587006 0.45658584 0.86093325]]

 [[0.94665052 0.16754013 0.77931293]
  [0.47217239 0.5887745  0.54856234]
  [0.9204112  0.76483227 0.03705401]]

 [[0.04033457 0.14781515 0.44663371]
  [0.54601418 0.08564348 0.29245086]
  [0.72774449 0.6208349  0.51009537]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
import random
b=np.random.randint(20,size=(5,5))
print('original matrix: ')
print(b)
for i in range(0,len(b)):
    for j in range(0,len(b)):
        if i>j:
            b[i][j]=random.randint(1,5)
print('new matrix:')
print(b)
    

original matrix: 
[[11  8  5  6 19]
 [12  1 19  1 10]
 [ 0  8 13  8 13]
 [ 4  5 10  7 13]
 [17  7  9 12  1]]
new matrix:
[[11  8  5  6 19]
 [ 2  1 19  1 10]
 [ 2  1 13  8 13]
 [ 2  5  1  7 13]
 [ 1  1  3  2  1]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
a2=np.zeros((8,8),dtype='int')
a2[::2,1::2]=1
a2[1::2,::2]=1
print(a2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
arr=np.random.randint(130,size=(5,5))
print('original array:')
print(arr)
new_arr=(arr-arr.min())/(arr.max()-arr.min())
print('Normalized Array:')
print(new_arr)

original array:
[[ 34 119   0  20 108]
 [128  90 122  38 105]
 [ 57  46  54  96 126]
 [ 14   6  88  21  66]
 [ 75   4  26 104   8]]
Normalized Array:
[[0.265625  0.9296875 0.        0.15625   0.84375  ]
 [1.        0.703125  0.953125  0.296875  0.8203125]
 [0.4453125 0.359375  0.421875  0.75      0.984375 ]
 [0.109375  0.046875  0.6875    0.1640625 0.515625 ]
 [0.5859375 0.03125   0.203125  0.8125    0.0625   ]]


# 5.  How to find common values between two arrays?

In [6]:
a3=np.array([10,20,30,40,50])
a4=np.array([20,25,40,45])
a5=np.intersect1d(a3,a4)
print('Common Values: ',a5)

Common Values:  [20 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday=np.datetime64('today','D') - np.timedelta64(1,'D')
print('Yestraday: ',yesterday)
today= np.datetime64('today','D')
print('Today: ',today)
tomorrow=np.datetime64('today','D') + np.timedelta64(1,'D')
print('Tomorrow: ',tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [8]:
A=np.array([[2,3,4],[6,4,8],[10,9,7]])
B=np.array([[2,3,4],[6,4,8]])
np.array_equal(A,B)

False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
arr1=np.random.randint(30,size=10)
print('original Array: ',arr1)
arr1[arr1.argmax()]=0
print('New array: ',arr1)

original Array:  [17  7  6  3 29  1  4 25 26 12]
New array:  [17  7  6  3  0  1  4 25 26 12]


# 9. How to print all the values of an array?

In [10]:
arr2=np.array([10,14,17,20,24])
for i in arr2:
    print(i)

10
14
17
20
24


# 10.Subtract the mean of each row of a matrix

In [11]:
arr3=np.array([[2,3,4],[6,4,8],[10,9,7]])
mean_arr=np.mean(arr3,axis=1)
x=np.array([mean_arr]).T
new=arr3-x
print('Mean array:')
print(x)
print('After subtracting mean array: ')
print(new)

Mean array:
[[3.        ]
 [6.        ]
 [8.66666667]]
After subtracting mean array: 
[[-1.          0.          1.        ]
 [ 0.         -2.          2.        ]
 [ 1.33333333  0.33333333 -1.66666667]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
c=np.array([10,15,20,25,35,38,42,56,60,70])
index=np.random.randint(len(c),size=4)
print('Given Vector: ',c)
print('index vector: ',index)
l=[]
for i in index:
    if i not in l:
        l.append(i)
new_in=np.array(l)
print('New index vector: ',new_in)
for i in new_in:
    c[i]=c[i]+1
print('new vector: ',c)

Given Vector:  [10 15 20 25 35 38 42 56 60 70]
index vector:  [0 3 1 1]
New index vector:  [0 3 1]
new vector:  [11 16 20 26 35 38 42 56 60 70]


# 12.How to get the diagonal of a dot product?

In [13]:
ar1=np.array([[1,2,3],[2,3,1],[5,6,7]])
ar2=np.array([[3,4,5],[2,4,3],[9,8,3]])
dp=np.dot(ar1,ar2)
print('Dot Product array: ')
print(dp)
diagonal=np.diag(dp)
print('Diagonal: ',diagonal)

Dot Product array: 
[[ 34  36  20]
 [ 21  28  22]
 [ 90 100  64]]
Diagonal:  [34 28 64]


# 13.How to find the most frequent value in an array?

In [14]:
d=np.array([10,20,30,32,20,56,45,32,32,10,32])
print('Original array:')
print(d)
print('Most frequent value:')
print(np.bincount(d).argmax())

Original array:
[10 20 30 32 20 56 45 32 32 10 32]
Most frequent value:
32


# 14.How to get the n largest values of an array

In [15]:
def num(n):
    a=np.arange(12)
    print('Original array: ',a)
    print('n largest values in array: ',a[np.argsort(a)[-n:]])

In [16]:
num(4)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
n largest values in array:  [ 8  9 10 11]


# 15.How to create a record array from a regular array?

In [17]:
a1=np.array([1,2,3,4])
a2=np.array(['Hi','Ai-ml','team','learners'])
a3=np.array([12,15,20,34])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result)

[(1, 'Hi', 12) (2, 'Ai-ml', 15) (3, 'team', 20) (4, 'learners', 34)]
